addSbtPlugin("org.wartremover" % "sbt-wartremover" % "2.4.10")
addSbtPlugin("com.lucidchart"  % "sbt-scalafmt"    % "1.16")
addSbtPlugin("org.scoverage"   % "sbt-scoverage"   % "1.6.1")
addSbtPlugin("org.scoverage"   % "sbt-coveralls"   % "1.2.7")
addSbtPlugin("ch.epfl.scala"   % "sbt-scalafix"    % "0.9.21")
