addSbtPlugin("org.wartremover"  % "sbt-wartremover" % "3.1.6")
addSbtPlugin("com.lucidchart"   % "sbt-scalafmt"    % "1.16")
addSbtPlugin("org.scoverage"    % "sbt-scoverage"   % "2.0.9")
addSbtPlugin("org.scoverage"    % "sbt-coveralls"   % "1.2.7")
addSbtPlugin("ch.epfl.scala"    % "sbt-scalafix"    % "0.11.1")
addSbtPlugin("com.github.sbt"   % "sbt-ci-release"  % "1.5.12")
