addSbtPlugin("org.wartremover" % "sbt-wartremover" % "2.1.1")
addSbtPlugin("com.lucidchart" % "sbt-scalafmt" % "1.10")
addSbtPlugin("org.scoverage"   % "sbt-scoverage"   % "1.5.0")
addSbtPlugin("org.scoverage"   % "sbt-coveralls"   % "1.1.0")
addSbtPlugin("com.eed3si9n" % "sbt-doge" % "0.1.5")